### ISSUE TITLE
'@apocentre/bc-ur' in deps

### ISSUE THREAD

**Issue by Overtorment** [KeystoneHQ/ur-registry#1]
I see `@apocentre/bc-ur` is in dependencies and its used in `src/RegistryItem.ts`.
And at the same time, this lib requires outside code to use `@apocentre/bc-ur` as well to first decode CBOR to pass it then to `ur-registry`.
This doesn't make much sense, this library should either fully handle CBOR stuff and relieve outside code from this burden OR allow outside code to do CBOR stuff on its own, thus reducing number of dependencies for this lib (zero deps is the target, as dependencies are always a risk in our line of work)

**Comment by Overtorment** [comment]
not to mention `@apocentre/bc-ur` is not very reputable, and has too many dependencies. risky.

**Comment by soralit** [comment]
Nice point. Already extended `bc-ur` in this lib.
