### ISSUE TITLE
Update bc-ur dependency

### ISSUE THREAD

**Issue by AndreasGassmann** [KeystoneHQ/ur-registry#3]
According to [this issue](https://github.com/ngraveio/bc-ur/issues/5), the package has been moved to `@ngraveio/bc-ur`.

https://github.com/KeystoneHQ/ur-registry/blob/675fa8b4505a6f162ff64bd3e2294df0f77470d9/package.json#L70

**Comment by soralit** [comment]
Updated. Thanks.
